/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uchicago_cs_encsel_query_simdscan_SimdScanner */

#ifndef _Included_edu_uchicago_cs_encsel_query_simdscan_SimdScanner
#define _Included_edu_uchicago_cs_encsel_query_simdscan_SimdScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uchicago_cs_encsel_query_simdscan_SimdScanner
 * Method:    scanBitpacked
 * Signature: (Ljava/nio/ByteBuffer;IIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_uchicago_cs_encsel_query_simdscan_SimdScanner_scanBitpacked
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
