/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uchicago_cs_db_sboost_SimdScanner */

#ifndef _Included_edu_uchicago_cs_db_sboost_SimdScanner
#define _Included_edu_uchicago_cs_db_sboost_SimdScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uchicago_cs_db_sboost_SimdScanner
 * Method:    filterBP
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_uchicago_cs_db_sboost_SimdScanner_filterBP
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     edu_uchicago_cs_db_sboost_SimdScanner
 * Method:    filterRLE
 * Signature: (Ljava/nio/ByteBuffer;III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_uchicago_cs_db_sboost_SimdScanner_filterRLE
  (JNIEnv *, jobject, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
